version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
    volumes_from:
      - nginx-proxy:rw
    environment:
      - DEFAULT_EMAIL=pau.baguer@upc.edu

  # mongo:
  #   image: mongo:latest
  #   container_name: mongodb
  #   volumes:
  #     - mongodbData:/data/db

  backoffice:
    image: paubaguer/ea-backoffice:latest
    container_name: backoffice
    environment:
      - VIRTUAL_HOST=eabackoffice.crabdance.com
      - LETSENCRYPT_HOST=eabackoffice.crabdance.com

  webApp:
    image: paubaguer/ea-frontend:latest
    container_name: webApp
    environment:
      - VIRTUAL_HOST=eaweb.chickenkiller.com
      - LETSENCRYPT_HOST=eaweb.chickenkiller.com

  api:
    image: paubaguer/ea-backend:latest
    container_name: api
    environment:
      - VIRTUAL_HOST=eaapi.chickenkiller.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=eaapi.chickenkiller.com

  jovoApi:
    image: paubaguer/ea-jovobackend:latest
    container_name: jovobackend
    environment:
      - VIRTUAL_HOST=eajovo.chickenkiller.com
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=eajovo.chickenkiller.com
# volumes:
#   mongodbData:
